In [ ]:
import pandas as pd
import os
import json


def get_pd_df(path):
    
    total_dict = {
        'file_name': [],
        'dict': [],
        'step': []
    }

    for i in [x[0] for x in os.walk(path)]:
        eval_result = read_json(os.path.join(i, 'eval_scores.json'))
        config = read_json(os.path.join(i, 'ckpt_eval.json'))
        if eval_result != None:
            for single_eval in eval_result:
                total_dict['dict'].append(os.path.basename(i))
                total_dict['file_name'].append(single_eval)
                
                for key in eval_result[single_eval]:
                    if key in total_dict:
                        total_dict[key].append(eval_result[single_eval][key])
                    else:
                        total_dict.update({key: [eval_result[single_eval][key]]})
                        
                total_dict['step'].append(int(''.join([x if x.isdigit() else '' for x in single_eval])))
                for key in config:
                    if key in total_dict:
                        total_dict[key].append(config[key])
                    else:
                        total_dict.update({key: [config[key]]})
                        
    df = pd.DataFrame.from_dict(total_dict)
    df['SUM'] = df['AP']  + df['AP50'] + df['AP75'] + \
                df['APs'] + df['APm']  + df['APl']
    sum_c = df['SUM']
    df.drop(labels=['SUM'], axis=1,inplace = True)
    df.insert(0, 'SUM', sum_c)
    return df

In [14]:
import os, json
import pandas as pd
import os
import json

folder = "output_aug"
path = os.path.join(folder, "score_of_models.json")
with open(path) as f:
    data = json.load(f)

total_dict = {
    'data_set': [],
    'file_name': [],
    'AP': [],
    'AP50': [],
    'AP75': [],
    'APs': [],
    'APm': [],
    'APl': []
}
for z in data:
    for s in data[z]:
        total_dict['AP'].append(data[z][s]['segm']['AP'])
        total_dict['AP50'].append(data[z][s]['segm']['AP50'])
        total_dict['AP75'].append(data[z][s]['segm']['AP75'])
        
        total_dict['APs'].append(data[z][s]['segm']['APs'])
        total_dict['APm'].append(data[z][s]['segm']['APm'])
        total_dict['APl'].append(data[z][s]['segm']['APl'])
        total_dict['file_name'].append(z)
        total_dict['data_set'].append(s)
        
df = pd.DataFrame.from_dict(total_dict)
df['SUM'] = df['AP']  + df['AP50'] + df['AP75'] + \
            df['APs'] + df['APm']  + df['APl']
sum_c = df['SUM']
df.drop(labels=['SUM'], axis=1,inplace = True)
df.insert(0, 'SUM', sum_c)
df.sort_values(by=['file_name'], ascending=False)

,SUM,data_set,file_name,AP,AP50,AP75,APs,APm,APl
37,399.703233,fishial_Test,model_final.pth,73.913599,89.341425,84.446195,22.835128,48.650241,80.516644
35,399.703233,fishial_Test,model_0099999.pth,73.913599,89.341425,84.446195,22.835128,48.650241,80.516644
38,404.823044,fishial_Test,model_0097499.pth,73.775441,89.556542,84.783398,27.234904,49.666069,79.806690
39,396.170985,fishial_Test,model_0094999.pth,73.519365,89.033968,84.168369,19.646025,50.110878,79.692380
40,404.491023,fishial_Test,model_0092499.pth,74.207136,89.213695,85.157326,25.482569,50.137956,80.292342
36,398.579650,fishial_Test,model_0089999.pth,73.525959,88.891202,84.640002,22.061168,49.536096,79.925223
31,400.155629,fishial_Test,model_0087499.pth,73.968414,89.386908,84.611159,21.256524,50.829294,80.103330
30,401.072898,fishial_Test,model_0084999.pth,73.966979,89.546444,84.847314,22.241090,50.315817,80.155255
33,398.337932,fishial_Test,model_0082499.pth,73.889978,89.479069,85.238319,20.560297,49.128382,80.041887
27,397.711544,fishial_Test,model_0079999.pth,73.748078,88.776967,84.536788,20.317937,50.249823,80.081952
29,398.795478,fishial_Test,model_0077499.pth,73.789224,88.916074,84.608681,21.729465,49.575720,80.176314
34,401.320542,fishial_Test,model_0074999.pth,74.034954,89.204545,85.005651,22.683851,50.363923,80.027619
28,403.581875,fishial_Test,model_0072499.pth,74.016934,89.555053,85.255626,23.804975,51.068745,79.880542
26,397.727393,fishial_Test,model_0069999.pth,73.680057,88.771677,84.414383,20.586383,50.508074,79.766818
32,402.420526,fishial_Test,model_0067499.pth,74.285944,89.401301,85.365655,22.051517,50.984253,80.331856
21,403.274301,fishial_Test,model_0064999.pth,74.445801,89.887590,85.694912,21.622071,51.503074,80.120853
24,407.576687,fishial_Test,model_0062499.pth,74.083261,89.706748,85.334141,27.279944,51.183183,79.989409
22,404.311745,fishial_Test,model_0059999.pth,73.964501,89.390959,85.149590,25.073027,50.693364,80.040304
18,403.169190,fishial_Test,model_0057499.pth,74.012272,89.464655,85.022117,26.078984,48.328403,80.262758
25,405.069323,fishial_Test,model_0054999.pth,74.008648,89.476222,85.147160,26.324677,50.068462,80.044153
19,401.828533,fishial_Test,model_0052499.pth,73.900694,89.180795,85.058701,24.037503,49.718319,79.932521
17,409.127858,fishial_Test,model_0049999.pth,74.872785,90.543037,85.617317,25.346853,52.224106,80.523762
23,405.099165,fishial_Test,model_0047499.pth,74.472639,89.976298,85.818358,23.450667,51.050185,80.331017
20,407.524848,fishial_Test,model_0044999.pth,74.604088,90.432687,85.584157,25.258580,51.402686,80.242650
8,406.130611,fishial_Test,model_0042499.pth,74.291948,90.315954,85.417636,24.507801,51.660518,79.936754
9,402.948824,fishial_Test,model_0039999.pth,74.102544,89.977613,84.953513,24.790615,48.911935,80.212603
7,402.628498,fishial_Test,model_0037499.pth,73.775372,89.517555,84.596882,24.337280,51.004715,79.396693
3,406.545390,fishial_Test,model_0034999.pth,74.047680,89.885365,85.385190,25.558301,52.132639,79.536216
12,410.140768,fishial_Test,model_0032499.pth,74.831694,90.782444,85.819707,25.929240,52.515856,80.261827
14,405.479106,fishial_Test,model_0029999.pth,74.255520,90.098348,85.370087,24.310672,51.380777,80.063702
6,405.821458,fishial_Test,model_0027499.pth,74.410921,90.325766,85.603497,22.978742,52.719148,79.783385
2,405.227210,fishial_Test,model_0024999.pth,74.293142,90.019072,85.253374,23.543412,52.252771,79.865438
5,408.294404,fishial_Test,model_0022499.pth,74.369686,90.106527,85.398512,25.819395,52.605493,79.994790
10,410.967103,fishial_Test,model_0019999.pth,74.711304,90.562847,85.774420,27.115889,52.606210,80.196433
13,408.517078,fishial_Test,model_0017499.pth,74.673394,90.594202,85.515328,25.365665,52.142913,80.225577
16,410.808243,fishial_Test,model_0014999.pth,74.327962,90.548596,85.696841,27.612379,53.041337,79.581127
15,407.608610,fishial_Test,model_0012499.pth,74.668285,90.716131,85.394228,25.139776,51.600633,80.089558
1,409.105176,fishial_Test,model_0009999.pth,74.536253,90.605769,85.533850,25.678519,52.740379,80.010406
0,411.018001,fishial_Test,model_0007499.pth,74.458706,90.594546,85.777616,27.098326,53.284006,79.804801
4,410.717296,fishial_Test,model_0004999.pth,74.704036,90.885342,85.880723,27.269429,51.819852,80.157913
11,409.858762,fishial_Test,model_0002499.pth,74.458880,90.247277,85.590182,26.813234,52.739728,80.009461